plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs

pnpMode: loose

packageExtensions:
  "*@*":
    dependenciesMeta:
      "fsevents":
        built: false
        optional: true
  "typescript@*":
    peerDependencies:
      "source-map-support": "x"
    peerDependenciesMeta:
      "source-map-support":
        optional: true
  "styled-jsx@*":
    peerDependenciesMeta:
      "react":
        optional: true
  "solid-styled-jsx@0.19.x":
    peerDependencies:
      "solid-js": "0.18.0 - 0.20"
  "@babel/plugin-syntax-jsx@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@babel/plugin-syntax-import-meta@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@firebase/auth-types@*":
    peerDependenciesMeta:
      "@firebase/app-types":
        optional: true
      "@firebase/util":
        optional: true
  "@firebase/auth-interop-types@*":
    peerDependenciesMeta:
      "@firebase/app-types":
        optional: true
