packageExtensions:
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint: x
      eslint-plugin-jsx-a11y: x
      eslint-plugin-react: x
    peerDependenciesMeta:
      eslint-plugin-import:
        optional: true
      eslint-plugin-react-hooks:
        optional: true
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: x

  "@babel/plugin-syntax-import-meta@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@babel/plugin-syntax-jsx@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true

  "@firebase/auth-interop-types@*":
    peerDependenciesMeta:
      "@firebase/app-types":
        optional: true
  "@firebase/auth-types@*":
    peerDependenciesMeta:
      "@firebase/app-types":
        optional: true
      "@firebase/util":
        optional: true
  firebase-admin@*:
    dependencies:
      "@firebase/app": x
  "@firebase/database@*":
    dependencies:
      "@firebase/app": x
  "@firebase/rules-unit-testing@*":
    dependencies:
      "@firebase/component": x
    peerDependenciesMeta:
      "@google-cloud/firestore":
        optional: true

  styled-jsx@*:
    peerDependenciesMeta:
      react:
        optional: true

  promise-inflight@*:
    peerDependencies:
      bluebird: x
  cacache@*:
    peerDependencies:
      bluebird: x

  follow-redirects@*:
    peerDependencies:
      debug: x
  http-proxy@*:
    peerDependencies:
      debug: x

  snowpack@*:
    dependencies:
      bluebird: x
      debug: x

  typescript@*:
    dependencies:
      source-map-support: x
  "@types/node@*":
    dependencies:
      url: x
      querystring: x
  debug@*:
    dependencies:
      supports-color: x
  "@protobufjs/inquire@*":
    dependencies:
      long: x

  rollup@*:
    dependencies:
      source-map-support: x

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

logFilters:
  - code: YN0062
    level: discard

yarnPath: .yarn/releases/yarn-2.4.0.cjs
