packageExtensions:
  "@babel/plugin-syntax-import-meta@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@babel/plugin-syntax-jsx@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
  "@firebase/auth-interop-types@*":
    peerDependenciesMeta:
      "@firebase/app-types":
        optional: true
  "@firebase/auth-types@*":
    peerDependenciesMeta:
      "@firebase/app-types":
        optional: true
      "@firebase/util":
        optional: true
  "@firebase/database@*":
    peerDependencies:
      "@firebase/app": x
  "@firebase/rules-unit-testing@*":
    peerDependencies:
      "@firebase/component": x
    peerDependenciesMeta:
      "@google-cloud/firestore":
        optional: true
  "@protobufjs/inquire@*":
    peerDependenciesMeta:
      long:
        optional: true
  "@types/node@*":
    peerDependenciesMeta:
      querystring:
        optional: true
      url:
        optional: true
  cacache@*:
    peerDependencies:
      bluebird: x
  debug@*:
    peerDependenciesMeta:
      supports-color:
        optional: true
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint: x
      eslint-plugin-jsx-a11y: x
      eslint-plugin-react: x
    peerDependenciesMeta:
      eslint-plugin-import:
        optional: true
      eslint-plugin-react-hooks:
        optional: true
  firebase-admin@*:
    peerDependencies:
      "@firebase/app": x
  follow-redirects@*:
    peerDependencies:
      debug: x
  http-proxy@*:
    peerDependencies:
      debug: x
  postcss-import-url@*:
    peerDependencies:
      postcss: x
  promise-inflight@*:
    peerDependencies:
      bluebird: x
  snowpack@*:
    peerDependenciesMeta:
      bluebird:
        optional: true
      debug:
        optional: true
  solid-styled-jsx@*:
    peerDependencies:
      solid-js: x
  styled-jsx@*:
    peerDependenciesMeta:
      react:
        optional: true
  typescript@*:
    peerDependenciesMeta:
      source-map-support:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.3.3.cjs
